# References

Cotter,D. et al. (2006) LMPD: LIPID MAPS proteome database. Nucleic Acids Res., 34, D507–D510.

Frolkis,A. et al. (2010) SMPDB: The Small Molecule Pathway Database. Nucleic Acids Res., 38, D480–D487.

Jassal,B. et al. (2020) The reactome pathway knowledgebase. Nucleic Acids Res., 48, D498–D503.

Kanehisa,M. and Goto,S. (2000) KEGG: kyoto encyclopedia of genes and genomes. Nucleic Acids Res., 28, 27–30.

Liberzon,A. et al. (2015) The Molecular Signatures Database (MSigDB) hallmark gene set collection. Cell Syst., 1, 417–425.

Martens,M. et al. (2020) WikiPathways: connecting communities. Nucleic Acids Res.

Subramanian,A. et al. (2005) Gene set enrichment analysis: A knowledge-based approach for interpreting genome-wide expression profiles. Proc. Natl. Acad. Sci., 102, 15545 LP – 15550.

The Gene Ontology Consortium (2019) The Gene Ontology Resource: 20 years and still GOing strong. Nucleic Acids Res., 47, D330–D338.

Hasin, Yehudit. et al. (2017) "Multi-omics approaches to disease." Genome biology 18: 1-15.

Rabinowitz, Jeremy S., et al. (2017) "Transcriptomic, proteomic, and metabolomic landscape of positional memory in the caudal fin of zebrafish." Proceedings of the National Academy of Sciences 114.5: E717-E726.

Talman, Virpi, et al. (2018) "Molecular atlas of postnatal mouse heart development." Journal of the American Heart Association 7.20: e010378.

Yuan, Qihang, et al. (2022) "Integration of transcriptomics, proteomics, and metabolomics data to reveal HER2-associated metabolic heterogeneity in gastric cancer with response to immunotherapy and neoadjuvant chemotherapy." Frontiers in Immunology 13: 951137.

Li, Xin, Yan Du, and Wence Zhou. (2023) "Integrated transcriptomics, proteomics and metabolomics-based analysis uncover TAM2-associated glycolysis and pyruvate metabolic remodeling in pancreatic cancer." Frontiers in Immunology 14: 1170223.

Williams, Evan G., et al. (2022) "Multiomic profiling of the liver across diets and age in a diverse mouse population." Cell Systems 13.1: 43-57.

Iturria-Medina, Yasser, et al. (2022) "Unified epigenomic, transcriptomic, proteomic, and metabolomic taxonomy of Alzheimer’s disease progression and heterogeneity." Science Advances 8.46: eabo6764.

Kodam, Pradeep, et al. (2023) "Integrated multi-omics analysis of Alzheimer’s disease shows molecular signatures associated with disease progression and potential therapeutic targets." Scientific Reports 13.1: 3695.

Ghosh, Nilanjana, et al. (2016) "Transcriptomics, proteomics and metabolomics driven biomarker discovery in COPD: an update." Expert review of molecular diagnostics 16.8: 897-913.

Sun, Quan, et al. (2019) "Integration of metabolomic and transcriptomic profiles to identify biomarkers in serum of lung cancer." Journal of Cellular Biochemistry 120.7: 11981-11989.

Ren, Shancheng, et al. (2016) "Integration of metabolomics and transcriptomics reveals major metabolic pathways and potential biomarker involved in prostate cancer." Molecular & Cellular Proteomics 15.1: 154-163.

Jang, Yeongjun, et al. (2016)"MONGKIE: an integrated tool for network analysis and visualization for multi-omics data." Biology direct 11: 1-9.

Schultheis, Hendrik, et al. (2019) "WIlsON: web-based interactive omics visualization." Bioinformatics 35.6: 1055-1057.

Brademan, Dain R., et al. (2020) "Argonaut: A web platform for collaborative multi-omic data visualization and exploration." Patterns 1.7.

Ghosh, Soumita, et al. (2021) "multiSLIDE is a web server for exploring connected elements of biological pathways in multi-omics data." Nature Communications 12.1: 2279.

Zhou, Guangyan, et al. (2021) "OmicsAnalyst: a comprehensive web-based platform for visual analytics of multi-omics data." Nucleic Acids Research 49.W1: W476-W482.

Zoppi, Johanna, et al. (2021) "MiBiOmics: an interactive web application for multi-omics data exploration and integration." BMC bioinformatics 22: 1-14.

Liu, Tianyuan, et al. (2022) "PaintOmics 4: new tools for the integrative analysis of multi-omics datasets supported by multiple pathway databases." Nucleic Acids Research 50.W1: W551-W559.

Gu, Zuguang, et al. (2016) "Complex heatmaps reveal patterns and correlations in multidimensional genomic data." Bioinformatics 32.18: 2847-2849.

Gu, Zuguang. (2022) "Complex heatmap visualization." Imeta 1.3: e43.

Korotkevich, Gennady, et al. (2016) "Fast gene set enrichment analysis." BioRxiv: 060012.

Langfelder, Peter, and Steve Horvath. (2008) "WGCNA: an R package for weighted correlation network analysis." BMC bioinformatics 9: 1-13.

Akhmedov, Murodzhon, et al. (2017) "PCSF: An R-package for network-based interpretation of high-throughput data." PLoS computational biology 13.7 : e1005694.

Luo, Weijun, and Cory Brouwer. (2013) "Pathview: an R/Bioconductor package for pathway-based data integration and visualization." Bioinformatics 29.14: 1830-1831.

Gao, Benbo, et al. (2021) "Quickomics: exploring omics data in an intuitive, interactive and informative manner." Bioinformatics 37.20: 3670-3672.
